name: flutter_map_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  openapi:
    path: ./openapi/dist_http

  google_maps_flutter: ^2.7.0
  geolocator: ^11.0.0
  url_launcher: ^6.3.0
  auto_size_text: ^3.0.0
  flutter_svg: ^2.0.9
  collection: ^1.18.0
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.5.1

dev_dependencies:
  analyzer: ^6.4.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.10
  freezed: ^2.5.2
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/images/
