name: Analysis
env:
  TZ: "Asia/Tokyo"
  FLUTTER_VERSION: '3.19.6'
on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
      - name: check flutter version
        run: flutter --version
      - name: Install packages
        run: flutter pub get
      - name: run build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Linter
        run: flutter analyze
#      - name: Test
#        run: flutter test
